---
- name: check ls
  shell: |
    ls -a

- name: check every file
  shell: |
    find . -type f -printf "%T@ %p\n" | sort -nr | cut -d\  -f2-
    
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start